export const actionsTypes = {
  ADD_NEW_ORDER: "ADD_NEW_ORDER",
  DELETE_ORDER: "DELETE_ORDER",
  SELECT_ORDER: "SELECT_ORDER",
  ADD_PRODUCT_TO_ORDER: "ADD_PRODUCT_TO_ORDER",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  SET_PRODUCT_KEY_TYPE: "SET_PRODUCT_KEY_TYPE"
};
